function sys = mylinearizemodel(op)
% MYLINEARIZE Linearize the Simulink model - System_Design_Quadrocopter.
%
% SYS = MYLINEARIZE(OP) linearizes the Simulink model System_Design_Quadrocopter about
% the operating point OP.

% M-File generated by MATLAB(R) 7.10 and Simulink Control Design (TM) 3.1.
%
% Generated on: 05-Jul-2011 15:00:15

%% Specify the model name
model = 'System_Design_Quadrocopter';

%% Create the linearization I/O as specified in System_Design_Quadrocopter
ios(2) = linio('System_Design_Quadrocopter/Quadrocopter/Dynamics/From9',1,'out');
ios(1) = linio('System_Design_Quadrocopter/Quadrocopter/theta',1,'in');

%% Linearize the model
sys = linearize(model,op,ios);

%% Plot the resulting linearization.
pzmap(sys)
