/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Setting.java
 *
 * Created on 25-Apr-2010, 21:22:34
 */

package simpleread;

import javax.swing.JFileChooser;
import javax.swing.JFrame;

/**
 *
 * @author mediamarkt
 */
public class Setting extends javax.swing.JFrame {

    /** Creates new form Setting */
    public Setting() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        State_panel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        X_axis_p_state = new javax.swing.JEditorPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        X_axis_i_state = new javax.swing.JEditorPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        X_axis_d_state = new javax.swing.JEditorPane();
        jScrollPane7 = new javax.swing.JScrollPane();
        yaw_p_state = new javax.swing.JEditorPane();
        jScrollPane8 = new javax.swing.JScrollPane();
        yaw_i_state = new javax.swing.JEditorPane();
        jScrollPane9 = new javax.swing.JScrollPane();
        yaw_d_state = new javax.swing.JEditorPane();
        jScrollPane10 = new javax.swing.JScrollPane();
        Pitch_p_state = new javax.swing.JEditorPane();
        jScrollPane11 = new javax.swing.JScrollPane();
        Pitch_i_state = new javax.swing.JEditorPane();
        jScrollPane12 = new javax.swing.JScrollPane();
        Pitch_d_state = new javax.swing.JEditorPane();
        jLabel16 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        button1 = new java.awt.Button();
        button3 = new java.awt.Button();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane17 = new javax.swing.JScrollPane();
        lpR = new javax.swing.JTextPane();
        jScrollPane13 = new javax.swing.JScrollPane();
        lpP = new javax.swing.JTextPane();
        jScrollPane14 = new javax.swing.JScrollPane();
        hpR = new javax.swing.JTextPane();
        jScrollPane15 = new javax.swing.JScrollPane();
        hpP = new javax.swing.JTextPane();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane16 = new javax.swing.JScrollPane();
        inertiaX = new javax.swing.JTextPane();
        jScrollPane18 = new javax.swing.JScrollPane();
        inertiaY = new javax.swing.JTextPane();
        jScrollPane19 = new javax.swing.JScrollPane();
        inertiaZ = new javax.swing.JTextPane();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane20 = new javax.swing.JScrollPane();
        lenBoom = new javax.swing.JTextPane();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        button2 = new java.awt.Button();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        User_Settings = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        SaveSettingsMenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Setting of Gorvenors");

        jTabbedPane1.setBackground(new java.awt.Color(153, 153, 153));

        State_panel.setBackground(new java.awt.Color(153, 153, 153));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel2.setText("Pitch control");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel5.setText("X-axis Control");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel7.setText("Yaw Control");

        jScrollPane4.setViewportView(X_axis_p_state);

        jScrollPane5.setViewportView(X_axis_i_state);

        jScrollPane6.setViewportView(X_axis_d_state);

        jScrollPane7.setViewportView(yaw_p_state);

        jScrollPane8.setViewportView(yaw_i_state);

        jScrollPane9.setViewportView(yaw_d_state);

        jScrollPane10.setViewportView(Pitch_p_state);

        jScrollPane11.setViewportView(Pitch_i_state);

        jScrollPane12.setViewportView(Pitch_d_state);

        jLabel16.setText("D");

        jLabel8.setText("I");

        jLabel9.setText("P");

        jLabel10.setText("P");

        jLabel11.setText("I");

        jLabel12.setText("D");

        jLabel13.setText("P");

        jLabel14.setText("I");

        jLabel15.setText("D");

        button1.setLabel("Parametr Update");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });

        button3.setActionCommand("Parametr Response");
        button3.setLabel("Parametr Response");
        button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button3ActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel17.setText("LowPass Filter");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel18.setText("HighPass Filter");

        jScrollPane17.setViewportView(lpR);

        jScrollPane13.setViewportView(lpP);

        jScrollPane14.setViewportView(hpR);

        jScrollPane15.setViewportView(hpP);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel20.setText("Inertia");

        jScrollPane16.setViewportView(inertiaX);

        jScrollPane18.setViewportView(inertiaY);

        jScrollPane19.setViewportView(inertiaZ);

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel21.setText("Boom");

        jScrollPane20.setViewportView(lenBoom);

        jLabel22.setText("lpR");

        jLabel23.setText("hpR");

        jLabel24.setText("lpP");

        jLabel25.setText("hpP");

        jLabel26.setText("InertiaX");

        jLabel27.setText("InertiaY");

        jLabel28.setText("InertiaZ");

        jLabel29.setText("lenBoom");

        button2.setLabel("Parametr Request");
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout State_panelLayout = new javax.swing.GroupLayout(State_panel);
        State_panel.setLayout(State_panelLayout);
        State_panelLayout.setHorizontalGroup(
            State_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(State_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(State_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(State_panelLayout.createSequentialGroup()
                        .addGroup(State_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel24)
                            .addComponent(jLabel22))
                        .addGap(18, 18, 18)
                        .addGroup(State_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane17, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                            .addComponent(jLabel17)
                            .addComponent(jScrollPane13))
                        .addGap(3, 3, 3))
                    .addGroup(State_panelLayout.createSequentialGroup()
                        .addGroup(State_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(State_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(State_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(State_panelLayout.createSequentialGroup()
                        .addGroup(State_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(State_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel16)
                                .addComponent(jLabel8))
                            .addGroup(State_panelLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(State_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel23)
                                    .addComponent(jLabel25))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(State_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, State_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.LEADING, 0, 0, Short.MAX_VALUE)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane15, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, State_panelLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(State_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)))
                .addGroup(State_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(State_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, State_panelLayout.createSequentialGroup()
                            .addGap(18, 18, 18)
                            .addGroup(State_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel15)
                                .addComponent(jLabel13))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(State_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7)
                                .addComponent(jLabel20)))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, State_panelLayout.createSequentialGroup()
                            .addGap(8, 8, 8)
                            .addGroup(State_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel26)
                                .addComponent(jLabel27)
                                .addComponent(jLabel28))
                            .addGap(18, 18, 18)
                            .addGroup(State_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane18, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                                .addComponent(jScrollPane16)
                                .addComponent(jScrollPane19, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE))))
                    .addGroup(State_panelLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jLabel19)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(State_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(State_panelLayout.createSequentialGroup()
                        .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(State_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(State_panelLayout.createSequentialGroup()
                            .addComponent(jLabel29)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(State_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel21)
                                .addComponent(jScrollPane20, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE))
                            .addContainerGap(421, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(State_panelLayout.createSequentialGroup()
                            .addGroup(State_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(button1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(button3, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addContainerGap()))))
        );
        State_panelLayout.setVerticalGroup(
            State_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, State_panelLayout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addGroup(State_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, State_panelLayout.createSequentialGroup()
                        .addGroup(State_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(State_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(State_panelLayout.createSequentialGroup()
                                .addComponent(jScrollPane10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, State_panelLayout.createSequentialGroup()
                                .addGroup(State_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(State_panelLayout.createSequentialGroup()
                                        .addGroup(State_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9)
                                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(State_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8)
                                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabel13))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(State_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel15)
                                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(State_panelLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel11)
                                .addGap(14, 14, 14)
                                .addComponent(jLabel12))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, State_panelLayout.createSequentialGroup()
                        .addGroup(State_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, State_panelLayout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(State_panelLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel29, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(6, 6, 6)
                        .addGroup(State_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34)
                .addGroup(State_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, State_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel17)
                        .addComponent(jLabel18)
                        .addComponent(jLabel20))
                    .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(State_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(State_panelLayout.createSequentialGroup()
                        .addComponent(button3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(State_panelLayout.createSequentialGroup()
                        .addGroup(State_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(State_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jScrollPane17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel26))
                            .addComponent(jLabel22)
                            .addComponent(jLabel23))
                        .addGroup(State_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(State_panelLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(State_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel25)
                                    .addComponent(jLabel24)
                                    .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(State_panelLayout.createSequentialGroup()
                                        .addComponent(jScrollPane18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(State_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jScrollPane19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(State_panelLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel27)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel28)))))
                .addGap(72, 72, 72))
        );

        jTabbedPane1.addTab("State", State_panel);

        jMenu1.setText("File");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        User_Settings.setText("User Settings Download");
        User_Settings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                User_SettingsActionPerformed(evt);
            }
        });
        jMenu1.add(User_Settings);

        jMenuItem2.setText("Dedault Settings Download");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        SaveSettingsMenu.setText("Save Settings as");
        SaveSettingsMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveSettingsMenuActionPerformed(evt);
            }
        });
        jMenu1.add(SaveSettingsMenu);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1014, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jMenu1ActionPerformed

    private void User_SettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_User_SettingsActionPerformed
        // TODO add your handling code here:
     //   textField1.setText(PropMgr.readProps_details());
        String t;
     // PropMgr.writeProps();
        final  JFileChooser chooser1 = new JFileChooser(".");
       // chooser1.setCurrentDirectory(new java.io.File("."));
        chooser1.setVerifyInputWhenFocusTarget(true);
//        ImageFilter filter = new ImageFilter();
  //      filter.addType("properties");
     //   chooser1.addChoosableFileFilter(filter);
        chooser1.setAcceptAllFileFilterUsed(true);
        int returnVal =chooser1.showOpenDialog(chooser1);

        if(returnVal ==JFileChooser.APPROVE_OPTION){
        System.out.println("You chose a file named:"+chooser1.getSelectedFile().getPath());
        System.out.println(chooser1.getCurrentDirectory());
         //       Utils.getExtension(chooser1.getSelectedFile()));
        System.out.println(Utils.getExtension(chooser1.getSelectedFile()));
        System.out.println(Utils.getbody(chooser1.getSelectedFile()));
      // PropMgr.writePropssingle(Utils.getbody(chooser1.getSelectedFile()), jTextField1.getText());
        //Where to write down to, what


   /*     PropMgr.writeProps(Utils.getbody(chooser1.getSelectedFile()),
                Height_p_state.getText(),Height_i_state.getText(),Height_d_state.getText(),
                X_axis_p_state.getText(), X_axis_i_state.getText(),X_axis_d_state.getText(),
                Pitch_p_state.getText(),Pitch_i_state.getText(),Pitch_d_state.getText(),
                yaw_p_state.getText(),yaw_i_state.getText(),yaw_d_state.getText());
    */
     

      X_axis_p_state.setText(PropMgr.readProps(Utils.getbody(chooser1.getSelectedFile()),"x_axis_p"));
      X_axis_i_state.setText(PropMgr.readProps(Utils.getbody(chooser1.getSelectedFile()),"x_axis_i"));
      X_axis_d_state.setText(PropMgr.readProps(Utils.getbody(chooser1.getSelectedFile()),"x_axis_d"));

      Pitch_p_state.setText(PropMgr.readProps(Utils.getbody(chooser1.getSelectedFile()),"pitch_p"));
      Pitch_i_state.setText(PropMgr.readProps(Utils.getbody(chooser1.getSelectedFile()),"pitch_i"));
      Pitch_d_state.setText(PropMgr.readProps(Utils.getbody(chooser1.getSelectedFile()),"pitch_d"));

      yaw_p_state.setText(PropMgr.readProps(Utils.getbody(chooser1.getSelectedFile()),"yaw_p"));
      yaw_i_state.setText(PropMgr.readProps(Utils.getbody(chooser1.getSelectedFile()),"yaw_i"));
      yaw_d_state.setText(PropMgr.readProps(Utils.getbody(chooser1.getSelectedFile()),"yaw_d"));


      lpR.setText(PropMgr.readProps(Utils.getbody(chooser1.getSelectedFile()), "lpR"));

      lpP.setText(PropMgr.readProps(Utils.getbody(chooser1.getSelectedFile()), "lpP"));

      hpP.setText(PropMgr.readProps(Utils.getbody(chooser1.getSelectedFile()), "hpP"));
      inertiaX.setText(PropMgr.readProps(Utils.getbody(chooser1.getSelectedFile()), "inertiaX"));
      inertiaY.setText(PropMgr.readProps(Utils.getbody(chooser1.getSelectedFile()), "inertiaY"));
      inertiaZ.setText(PropMgr.readProps(Utils.getbody(chooser1.getSelectedFile()), "inertiaZ"));
      lenBoom.setText(PropMgr.readProps(Utils.getbody(chooser1.getSelectedFile()), "lenBoom"));


        
    }


        else {
        System.out.println("You did not choose a file");

        }

    }//GEN-LAST:event_User_SettingsActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
// PropMgr.defaultPropswrite();
      X_axis_p_state.setText(PropMgr.defaultPropsread("x_axis_p"));
      X_axis_i_state.setText(PropMgr.defaultPropsread("x_axis_i"));
      X_axis_d_state.setText(PropMgr.defaultPropsread("x_axis_d"));

      Pitch_p_state.setText(PropMgr.defaultPropsread("pitch_p"));
      Pitch_i_state.setText(PropMgr.defaultPropsread("pitch_i"));
      Pitch_d_state.setText(PropMgr.defaultPropsread("pitch_d"));

      yaw_p_state.setText(PropMgr.defaultPropsread("yaw_p"));
      yaw_i_state.setText(PropMgr.defaultPropsread("yaw_i"));
      yaw_d_state.setText(PropMgr.defaultPropsread("yaw_d"));
      lpR.setText(PropMgr.defaultPropsread("lpR"));
      lpP.setText(PropMgr.defaultPropsread("lpP"));
      hpP.setText(PropMgr.defaultPropsread("hpP"));
      inertiaX.setText(PropMgr.defaultPropsread("inertiaX"));
      inertiaY.setText(PropMgr.defaultPropsread("inertiaY"));
      inertiaZ.setText(PropMgr.defaultPropsread("inertiaZ"));
      lenBoom.setText(PropMgr.defaultPropsread("lenBoom"));
      


    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void SaveSettingsMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveSettingsMenuActionPerformed
        final  JFileChooser chooser1 = new JFileChooser(".");
       // chooser1.setCurrentDirectory(new java.io.File("."));
      //  ImageFilter filter = new ImageFilter();
      //  filter.addType("properties");
      //  chooser1.addChoosableFileFilter(filter);
      //  chooser1.setAcceptAllFileFilterUsed(true);
/*
        JFrame proba1=new JFrame();
        proba1.add(chooser1);
        proba1.setVisible(true);
  */

        int returnVal =chooser1.showDialog(chooser1,"Save as");

        
        if(returnVal ==JFileChooser.APPROVE_OPTION){
        System.out.println("You chose a file named:"+chooser1.getSelectedFile().getPath());

        System.out.println(Utils.getExtension(chooser1.getSelectedFile()));
        System.out.println(Utils.getbody(chooser1.getSelectedFile()));
      // PropMgr.writePropssingle(Utils.getbody(chooser1.getSelectedFile()), jTextField1.getText());
        //Where to write down to, what

        PropMgr.writeProps(Utils.getbody(chooser1.getSelectedFile()),
               
                X_axis_p_state.getText(), X_axis_i_state.getText(),X_axis_d_state.getText(),
                Pitch_p_state.getText(),Pitch_i_state.getText(),Pitch_d_state.getText(),
                yaw_p_state.getText(),yaw_i_state.getText(),yaw_d_state.getText(),lpR.getText(),
                lpP.getText(),hpP.getText(),inertiaX.getText(),inertiaY.getText(), inertiaZ.getText(),lenBoom.getText());

        
        }

        
        else {
        System.out.println("You did not choose a file");

        }


//FileOpenService
        // TODO add your handling code here:
    }//GEN-LAST:event_SaveSettingsMenuActionPerformed

    private void button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button3ActionPerformed
        //int []v1=new
        SimpleRead_parametr_response.Start();
       
}//GEN-LAST:event_button3ActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        

        int k0= Integer.parseInt(X_axis_p_state.getText());
        char t0=(char)k0;
        System.out.print(t0);
        int k1= Integer.parseInt( X_axis_i_state.getText());
        char t1=(char)k1;
        System.out.print(t1);
        int k2= Integer.parseInt(X_axis_d_state.getText());
        char t2=(char)k2;
        System.out.print(t2);
         int k3= Integer.parseInt(Pitch_p_state.getText());
        char t3=(char)k3;
         int k4= Integer.parseInt(Pitch_i_state.getText());
        char t4=(char)k4;
         int k5= Integer.parseInt(Pitch_d_state.getText());
        char t5=(char)k5;
         int k6= Integer.parseInt(yaw_p_state.getText());
        char t6=(char)k6;
         int k7= Integer.parseInt(yaw_i_state.getText());
        char t7=(char)k7;
         int k8= Integer.parseInt(yaw_d_state.getText());
        char t8=(char)k8;
         int k9= Integer.parseInt(lpR.getText());
        char t9=(char)k9;
        int k10= Integer.parseInt(hpR.getText());
        char t10=(char)k10;
        
         int k11= Integer.parseInt(lpP.getText());
        char t11=(char)k11;
        
         int k12= Integer.parseInt(hpP.getText());
        char t12=(char)k12;
         int k13= Integer.parseInt(inertiaX.getText());
        char t13=(char)k13;
         int k14= Integer.parseInt(inertiaY.getText());
        char t14=(char)k14;
         int k15= Integer.parseInt(inertiaZ.getText());
        char t15=(char)k15;
         int k16= Integer.parseInt(lenBoom.getText());
        char t16=(char)k16;
        
        PortSettings.SimpleWrite_update(t0, t1, t2, t3, t4, t5, t6, t7, t8, t9, t10, t11, t12, t13, t14, t15, t16);
        
        
         
        



    //    PortSettings.SimpleWrite();
}//GEN-LAST:event_button1ActionPerformed

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        PortSettings.SimpleWrite_Parametr_request();     
    }//GEN-LAST:event_button2ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Setting().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JEditorPane Pitch_d_state;
    private javax.swing.JEditorPane Pitch_i_state;
    private javax.swing.JEditorPane Pitch_p_state;
    private javax.swing.JMenuItem SaveSettingsMenu;
    private javax.swing.JPanel State_panel;
    private javax.swing.JMenuItem User_Settings;
    private javax.swing.JEditorPane X_axis_d_state;
    private javax.swing.JEditorPane X_axis_i_state;
    private javax.swing.JEditorPane X_axis_p_state;
    private java.awt.Button button1;
    private java.awt.Button button2;
    private java.awt.Button button3;
    private javax.swing.JTextPane hpP;
    private javax.swing.JTextPane hpR;
    private javax.swing.JTextPane inertiaX;
    private javax.swing.JTextPane inertiaY;
    private javax.swing.JTextPane inertiaZ;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JScrollPane jScrollPane16;
    private javax.swing.JScrollPane jScrollPane17;
    private javax.swing.JScrollPane jScrollPane18;
    private javax.swing.JScrollPane jScrollPane19;
    private javax.swing.JScrollPane jScrollPane20;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextPane lenBoom;
    private javax.swing.JTextPane lpP;
    private javax.swing.JTextPane lpR;
    private javax.swing.JEditorPane yaw_d_state;
    private javax.swing.JEditorPane yaw_i_state;
    private javax.swing.JEditorPane yaw_p_state;
    // End of variables declaration//GEN-END:variables

}
